# Generated by Django 3.2.25 on 2026-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20260107_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
