# Generated by Django 3.2.25 on 2026-06-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20260107_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(help_text='Product ID at time of order')),
                ('product_title', models.CharField(help_text='Snapshot of product title', max_length=255)),
                ('unit_price', models.PositiveIntegerField(help_text='Snapshot price per unit at order time')),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.PositiveIntegerField(help_text='unit_price * quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_id'], name='orders_orde_product_32ff41_idx'),
        ),
    ]
