name: Django Backend Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start containers
        run: docker-compose up -d

      - name: Run flake8 and pytest
        run: docker exec backend sh -c "flake8 && pytest ."

      - name: Stop containers
        if: always()
        run: docker compose down
